<?php

/**
 * DokuWiki Image Detail Template
 *
 *
 * LICENSE: This file is open source software (OSS) and may be copied under
 *          certain conditions. See COPYING file for details or try to contact
 *          the author(s) of this file in doubt.
 *
 * @license GPLv2 (https://www.gnu.org/licenses/gpl-2.0.html)
 * @author ARSAVA <dokuwiki@dev.arsava.com>
 * @author viasnake <https://github.com/viasnake/>
 * @link https://github.com/viasnake/dokuwiki-template-vector
 * @link https://www.dokuwiki.org/devel:templates
 */

//check if we are running within the DokuWiki environment
if (!defined("DOKU_INC")) {
    die();
}

//do a little trick to use all the layout generated by main.php:
//1) this file will be called from dokuwiki
//2) we are including the main.php and set the "vecdo" request value so
//   main.php includes the needed content from inc_detail.php at the correct
//   place.

//get the main.php and signal: include inc_detail.php

if (isset($INPUT) &&
    is_object($INPUT) &&
    method_exists($INPUT, "set")) {
    $INPUT->set("vecdo", "detail");
}
include tpl_incdir()."main.php";
